### ISSUE TITLE
How to use the example?

### ISSUE THREAD

**Issue by hxzqlh** [BoLaMN/wcjs-angular-example#1]
As the title says, can any body tell how to use the exaple?

Thanks!

**Comment by BoLaMN** [comment]
Hey, it's currently very much a wip and only runs successfully on OS X.

If you're using OS X then npm install && grunt build and for now to run it open the electron app within the folder and drop the build folder onto where it says "drop here" 

Again still a wip as the project I was building this for no longer exists so I haven't allocated much time to finish it. 

If you're on windows or nix within app.coffee config module where it asks for the location for WebChimera is currently getting populated wrong feel free to fix and create a pr if I don't get around to it first.

Cheers
